
version: 2
jobs:
  build:
    branches:
      only:
        - travis-test
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/src

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: echo something for test
          command: echo "I RAN TEST"
      - run:
          name: echo something for test
          command: echo "This merged to master"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          branches:
            only: master
